version: '2'
services:
  database:
    build: ./db
    environment:
        - MYSQL_ROOT_PASSWORD=rem
  controller:
    build: ./db_controller
    environment:
        - MYSQL_ENV=database
    ports:
     - "5555"
    depends_on:
        - "database"
    command: ["./wait-for-it.sh", "-t", "0", "database:3306", "--", "python3","test_query.py"]
  broker:
    image: uniflex/broker
    ports:
     - "8989:8989"
     - "8990:8990"
