---
- name: Wishrem experiment deployment
  hosts: harry
  tasks:
  - name: Copy code
    synchronize:
      src: ../../
      dest: ~/wishrem
      recursive: yes

  - name: Start docker services
    docker_service:
      project_src: ~/wishrem
      build: yes
      state: present
      restarted: true

- name: Wishrem experiment deployment
  hosts: nucs
  tasks:
  - name: Install packages
    apt: name="{{ item }}" state=present
    with_items:
    - wget
    - git
    - python
    - python-virtualenv
    - python-dev
    - python3-dev
    - python3-pip
    become: yes

  - name: Install pip packages
    pip:
      name: "{{ item }}"
      executable: pip3
      extra_args: -U
      editable: no
    with_items:
    - "git+https://github.com/uniflex/uniflex"
    - "git+https://github.com/uniflex/sbi"
    become: yes
  - name: Copy code
    synchronize:
      src: ../../
      dest: ~/wishrem
      recursive: yes
